# Claude 配置文件
version: "1.0"
last_updated: "2025-09-08"

# Agent 設定
agents:
  auto_detection: true
  max_recommendations: 8
  load_all_agents: true
  
# 專案設定  
projects:
  auto_profile_detection: true
  create_project_memory: true
  backup_conversations: false

# Git 同步設定
sync:
  enabled: true
  repository: "https://github.com/r90941022/claude-config.git"
  auto_update: false
  
# 備份設定
backup:
  retention_days: 30
  auto_backup: false
  exclude_patterns:
    - "*.log"
    - "projects/*/conversations/*.jsonl"
    
# 使用統計 (選擇性)
analytics:
  enabled: false
  track_agent_usage: false